# Fucking Around

In [1]:
import pandas as pd
import tensorflow as tf

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

## Build layers of NN

In [2]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [3]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.05496386,  0.23443131,  0.220687  ,  0.49845684, -0.2827264 ,
         0.05821636,  0.12827899, -0.32387662, -0.6110271 ,  0.03009728]],
      dtype=float32)

In [4]:
tf.nn.softmax(predictions).numpy()

array([[0.09144189, 0.12213155, 0.12046442, 0.159035  , 0.07281639,
        0.1023997 , 0.10983139, 0.06988079, 0.05243846, 0.09956042]],
      dtype=float32)

In [5]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [6]:
loss_fn(y_train[:1], predictions).numpy()

2.2788715

In [7]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [8]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 1s 627us/step - loss: 0.2977 - accuracy: 0.9130
Epoch 2/5
1875/1875 [==============================] - 1s 619us/step - loss: 0.1426 - accuracy: 0.9580
Epoch 3/5
1875/1875 [==============================] - 1s 614us/step - loss: 0.1081 - accuracy: 0.9673
Epoch 4/5
1875/1875 [==============================] - 1s 615us/step - loss: 0.0893 - accuracy: 0.9721
Epoch 5/5
1875/1875 [==============================] - 1s 607us/step - loss: 0.0733 - accuracy: 0.9775


In [9]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 0s - loss: 0.0716 - accuracy: 0.9777


[0.07155203074216843, 0.9776999950408936]

In [10]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [11]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.4643026e-07, 2.5519887e-08, 1.4346219e-06, 5.1576892e-05,
        3.8490464e-10, 5.4483638e-07, 2.2249786e-13, 9.9984622e-01,
        1.0724112e-06, 9.8796765e-05],
       [3.1682809e-08, 6.1562641e-06, 9.9999309e-01, 7.4312669e-07,
        1.2477350e-14, 2.1041593e-08, 1.1042863e-09, 3.9253767e-16,
        3.5277832e-09, 1.6633952e-14],
       [2.0439656e-07, 9.9813652e-01, 3.1159001e-05, 1.4205541e-05,
        1.2504830e-04, 4.1112326e-06, 6.7120018e-06, 1.1959049e-03,
        4.8453739e-04, 1.4927108e-06],
       [9.9992311e-01, 1.5823439e-08, 1.7099750e-05, 5.9112256e-07,
        9.6923247e-07, 2.8998660e-05, 4.3818231e-06, 2.9614393e-06,
        3.6527954e-09, 2.1960241e-05],
       [1.8529234e-06, 9.7983799e-09, 2.5452393e-06, 5.8726059e-08,
        9.9092507e-01, 1.3940232e-06, 3.2543572e-05, 7.4334792e-05,
        1.9662909e-06, 8.9602480e-03]], dtype=float32)>